apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-prod
  namespace: test
  labels:
    app: d-prod
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: d-prod
  template:
    metadata:
      labels:
        app: d-prod
    spec:
      containers:
      - name: d-container
        image: ozgurozturknet/k8s:v1
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80