apiVersion: v1
kind: Service
metadata:
  name: d-svc
  namespace: test
spec:
  selector:
    app: d-prod
  ports:
    - name: d-port
      port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer