apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test
spec:
  serviceAccountName: admin-sa
  containers:
  - name: test-pod
    image: ubuntu
    command: ['sh', '-c', 'apt update && apt install -y bash curl && sleep infinity']
