apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: senior-production-role-binding
  namespace: production
subjects:
- kind: User
  name: mucahid2@k8s
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: senior-production-role
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: senior-test-role-binding
  namespace: test
subjects:
- kind: User
  name: mucahid2@k8s
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: senior-test-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: senior-cluster-role-binding
subjects:
- kind: Group
  name: senior
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: senior-cluster-role
  apiGroup: rbac.authorization.k8s.io